apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: are-pvc
  labels:
    app: are
    app.kubernetes.io/component: runtime
    app.kubernetes.io/part-of: aigenzey-runtime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
