apiVersion: v1
kind: Secret
metadata:
  name: are-secret
  labels:
    app: are
    app.kubernetes.io/component: runtime
    app.kubernetes.io/part-of: aigenzey-runtime
type: Opaque
stringData:
  GOOGLE_API_KEY: ""
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  API_KEY: ""
  SECRET_KEY: "AGZalfjei0eowfpiBv4iu3h0f7j0hfcna8do"
  INSTANCEADMIN_EMAIL: "instanceadmin@aigenzey.com"
  INSTANCEADMIN_PASSWORD: "SecretPassword123"
  PODADMIN_EMAIL: "instanceadmin@aigenzey.com"
  PODADMIN_PASSWORD: "SecretPassword123"
  PODADMIN_TOKEN_TTL: "900"
