apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secret
  labels:
    app: ai-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: aigenzey-runtime
type: Opaque
stringData:
  INSTANCEADMIN_EMAIL: "instanceadmin@aigenzey.com"
  INSTANCEADMIN_PASSWORD: "SecretPassword123"
  PODADMIN_EMAIL: "instanceadmin@aigenzey.com"
  PODADMIN_PASSWORD: "SecretPassword123"
